
#          _            This file forms as the configuration runtime for
#        ,/_\,          testing each permutation of roughtime server and
#      ,/_/ \_\,        client. Somewhere in between we packet capture
#     /_/ ___ \_\       the server interface using netshoot and tcpdump.
#    /_/ |(V)| \_\
#      |  .-.  |        There's quite a lot of environment variables that have
#      | / / \ |        to be set here, including:
#      | \ \ / |        * SERVER_IMAGE - Name of the roughtime server
#      |  '-'  |        * CLIENT_IMAGE - Name of the roughtime client
#      '--,-,--'        * PERM_DIR     - Folder where the permutation keeps
#  jgs    | |                            all outputted files, like the pcap,
#         | |                            but also logs and anything else
#         | |
#         /\|
#         \/|
#          /\
#          \/

name: "plummet"
services:

  server:
    hostname: roughtime-server
    image: ${SERVER_IMAGE}
    pull_policy: never
    command: /run.sh server
    ports:
      -  2002:2002/udp
    volumes:
      - ${PERM_DIR}:/data
    networks:
       plummet:
         aliases:
           - roughtime-server

  client:
    hostname: roughtime-client
    image: ${CLIENT_IMAGE}
    pull_policy: never
    command: /run.sh client
    depends_on:
      - server
    volumes:
      - ${PERM_DIR}:/data
    networks:
       plummet:
         aliases:
           - roughtime-client

  server_pcap:
    image: nicolaka/netshoot
    depends_on:
      - server
    network_mode: service:server
    command: tcpdump -i eth0 -w /data/server.pcap
    volumes:
      - ${PERM_DIR}:/data

networks:
  plummet:
    enable_ipv4: true
    enable_ipv6: false